import { Input } from "./ui/input"
import { useState } from "react"

type EditableTextProps = {
    value: string
    onSave: (v: string) => void
}

//whole component generated by ChatGPT
export function EditableText({value, onSave}: EditableTextProps) {
    const [editing, setEditing] = useState(false)
    const [draft, setDraft] = useState(value)

    if (!editing) {
        return (
            <span
                onDoubleClick={() => setEditing(true)}
                className="cursor-text rounded px-1 hover:bg-muted"
            >
                {value}
            </span>
        )
    }

    return (
        <Input
            autoFocus
            value={draft}
            onChange={(e) => setDraft(e.target.value)}
            onFocus={(e) => e.target.select()}
            onBlur={() => {
                setEditing(false)
                onSave(draft)
            }}
            onKeyDown={(e) => {
                if (e.key === "Enter") {
                    setEditing(false)
                    onSave(draft)
                }
                if (e.key === "Escape") {
                    setEditing(false)
                    setDraft(value)
                }
            }}
            className="h-7 w-auto px-1"
        />
    )
}