import { Input } from "./ui/input"
import { useState, useRef, useEffect, useLayoutEffect } from "react"
import { AppContext, useAppContext } from "./context/globalContext"

type EditableTextProps = {
  value: string
  onSave: (v: string) => void,
  className?: string,
  validate?: (value: string) => boolean // validation function
  errorMessage?: string
}

//whole component generated by ChatGPT
export function EditableText(
  { value, onSave, className, validate = () => true,
    errorMessage = "Invalid file name"
  }: EditableTextProps) {

    const {currentFileId, updateFile} = useAppContext()

  const [editing, setEditing] = useState(false)
  const [draft, setDraft] = useState(value)
  const [inputWidth, setInputWidth] = useState(0)
  const [isValid, setIsValid] = useState(true)

  const spanRef = useRef<HTMLSpanElement>(null)
  const inputRef = useRef<HTMLInputElement>(null)

  // Update input width whenever text changes
  useLayoutEffect(() => {
    if (spanRef.current) {
      const width = spanRef.current.offsetWidth
      setInputWidth(width + 4) // small buffer for cursor
    }
  }, [draft])

  const finishEditing = () => {
    const valid = validate(draft)
    setIsValid(valid)
    onSave
  }

  if (!editing) {
    return (
      <span
        onDoubleClick={() => {
          setEditing(true)
          setDraft(value)
        }}
        className="cursor-text"
      >
        {value}
      </span>
    )
  }

  return (
    <>
      {/* Invisible span for measuring text */}
      <span
        ref={spanRef}
        className="absolute invisible whitespace-pre font-sans text-base"
      >
        {draft || ""}
      </span>

      <Input
        ref={inputRef}
        autoFocus
        value={draft}
        onChange={(e) => {
          setDraft(e.target.value)
          setIsValid(validate(e.target.value))
        }}
        onBlur={finishEditing}
        onKeyDown={(e) => {
          if (e.key === "Enter") finishEditing()
          if (e.key === "Escape") {
            setDraft(value)
            setIsValid(true)
            setEditing(false)
            updateFile(currentFileId, 
              {filename: value}
            )
          }
        }}
        style={{ width: inputWidth }}
        className={`h-7 px-1 transition-colors duration-100 ${isValid ? "" : "border border-red-500 outline-none"
          } ${className}`}
      />
      {!isValid && (
        <div className="text-red-500 text-xs mt-1 absolute">
          {errorMessage}
        </div>
      )}
    </>
  )
}