//this component is mainly generated by ChatGPT

import * as React from "react"
import { Check, ChevronsUpDown } from "lucide-react"
import { cn } from "./components/ui/lib/utils"
import { Button } from "./ui/button"
import { customOption } from "./popups/FilterPopup"
import {
  Command,
  CommandEmpty,
  CommandGroup,
  CommandItem,
} from "./ui/command"
import { Popover, PopoverContent, PopoverTrigger } from "./ui/popover"
import { useTranslation } from "react-i18next"
import { THEME } from "../theme"
import { useAppContext } from "./context/globalContext"
import clsx from "clsx"


interface MultiSelectProps {
  options: customOption[],
  value: Set<string>,
  onChange: (value: Set<string>) => void
}

export function MultiSelect({ options, value, onChange }: MultiSelectProps) {

  const { t } = useTranslation()
  const { lightMode } = useAppContext()
  const toggle = (val: string) => {
    const next = new Set(value) // copy the current Set from props
    if (next.has(val)) next.delete(val) // remove if already selected
    else next.add(val)                   // add if not selected
    onChange(next)                       // pass updated Set to parent
  }

  return (
    <Popover>
      <PopoverTrigger asChild>
        <Button
          variant="outline"
          role="combobox"
          className={clsx(THEME.menu.item(lightMode), "w-48 justify-between")}
        >
          {value.size
            ? `${value.size} selected`
            : "Select options"}
          <ChevronsUpDown className="ml-2 h-4 w-4 opacity-50" />
        </Button>
      </PopoverTrigger>

      <PopoverContent className={clsx(THEME.background(lightMode), "w-48 p-0")} >
        <Command>
          <CommandEmpty>{t("home.no-results")}</CommandEmpty>
          <CommandGroup>
            {Array.from(options).map(option => (
              <CommandItem
                key={option.value}
                onSelect={() => toggle(option.value!)}
              >
                <Check
                  className={cn(
                    "mr-2 h-4 w-4",
                    value.has(option.value!)
                      ? "opacity-100"
                      : "opacity-0"
                  )}
                />
                {option.label}
              </CommandItem>
            ))}
          </CommandGroup>
        </Command>
      </PopoverContent>
    </Popover>
  )
}